# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Parchment mappings, see https://github.com/neoforged/ModDevGradle#better-minecraft-parameter-names--javadoc-parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Environment properties.
# The Minecraft version must agree with the NeoForge version to get a valid artifact.
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.176
neo_version_range=[21.1.0,)
loader_version_range=[4,)

## Mod properties

# The unique mod identifier. Must match the String constant in the class annotated with @Mod.
mod_id=nomoretorchspam
# The human-readable display name.
mod_name=No More Torch Spam
mod_license=MIT
mod_version=1.0.0
# The group ID used when publishing the artifact.
mod_group_id=com.hagenberg.fh.nomoretorchspam
mod_authors=Tobias Filler, Lukas Hartinger
mod_description=A small mod that adds the Glow Crystal, a scalable light source. As it is a single block, it prevents the use of tons of torches, improving the look of your Minecraft World. :)